version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/forum_db
      - SPRING_DATASOURCE_USERNAME=forum_user
      - SPRING_DATASOURCE_PASSWORD=forum_password
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=forum_db
      - POSTGRES_USER=forum_user
      - POSTGRES_PASSWORD=forum_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
